services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx'
    restart: unless-stopped
      # ports:
      # These ports are in format <host-port>:<container-port>
      # - '80:80' # Public HTTP Port
      # - '443:443' # Public HTTPS Port
      # - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
      # - '82:82' #  drive.home.chun.no
      # - '6389:6389' #  drive.home.chun.no redis
      # - '83:83' #  qb.home.chun.no
      # - '8123:8123' #  ha.home.chun.no
      # - '32400:32400' #  plex.home.chun.no

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - /home/chun/docker/nginx/data:/data
      - /home/chun/docker/nginx/letsencrypt:/etc/letsencrypt
      - /home/chun/docker/nginx/custom:/etc/nginx/conf.d/custom
    network_mode: host

  wetty111:
    image: 'wettyoss/wetty'
    container_name: 'wetty111'
    restart: unless-stopped
    ports:
      - '3111:3000'
    command: --ssh-host=192.168.2.111

  wetty121:
    image: 'wettyoss/wetty'
    container_name: 'wetty121'
    restart: unless-stopped
    ports:
      - '3121:3000'
    command: --ssh-host=192.168.2.121

  home-assistant:
    image: 'ghcr.io/home-assistant/home-assistant:stable'
    container_name: 'home-assistant'
    restart: unless-stopped
    volumes:
      - /home/chun/docker/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    environment:
      DISABLE_JEMALLOC: true

  nextcloud:
    image: nextcloud:28
    container_name: 'nextcloud'
    restart: unless-stopped
    ports:
      - '82:80'
    volumes:
      - /home/chun/docker/nextcloud/config:/var/www/html/config
      - /mnt/nas1/shared:/var/www/html/data
    user: '1000:1000'
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    links:
      - nextcloud-db
      - nextcloud-redis
  nextcloud-db:
    image: postgres:15
    container_name: 'nextcloud-db'
    restart: unless-stopped
    ports:
      - '5482:5432'
    volumes:
      - /home/chun/docker/nextcloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  nextcloud-redis:
    image: redis
    container_name: 'nextcloud-redis'
    restart: unless-stopped
    ports:
      - '6389:6379'
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: 'plex'
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/chun/docker/plex/config:/config
      - /mnt/nas1/shared/chun/files/Music:/media/Music
      - /mnt/nas1/shared/chun/files/Movies:/media/Movies
      - /mnt/nas1/shared/chun/files/Media:/media/Media
    devices: 
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional

  qb:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/chun/docker/qbittorrent/appdata:/config
      - /home/chun/shared/downloads:/downloads #optional
    ports:
      - 83:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - /home/chun/docker/xray:/etc/xray
    ports:
      - 80:9000
    restart: unless-stopped

